version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache-ci
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php/src:/var/www/html/
      - ./php/src/uploads/images:/var/www/html/uploads/images  # Mount the uploads directory to the PHP container
      - ./php/src/uploads/videos:/var/www/html/uploads/videos
    ports:
      - "8080:80"
    command: /bin/bash -c "mkdir -p /var/www/html/uploads/videos && mkdir -p /var/www/html/uploads/images && apache2-foreground"  # Create the uploads/videos and uploads/images directories and start Apache

  db:
    container_name: db-ci
    # image: mysql:5.7
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskr_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: phpmyadmin-ci
    image: phpmyadmin/phpmyadmin
    ports:
        - '8081:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db